import { useEffect, useState } from "react";
import { Download, ImageOff, Loader2 } from "lucide-react";
import { cn } from "cn";
import type { ModelId } from "@/types";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";

type Props = {
  imageUrl: string;
  fallbackUrls?: string[];
  prompt?: string;
  model?: ModelId;
  width?: number;
  height?: number;
};

function GeneratingFrame({ className, style }: { className?: string; style?: React.CSSProperties }) {
  return (
    <div
      className={cn(
        "image-generation-frame relative flex items-center justify-center rounded-2xl border border-primary/25",
        className,
      )}
      style={style}
      role="status"
      aria-live="polite"
    >
      <span className="relative z-10 inline-flex items-center gap-2 text-sm font-medium tracking-tight">
        <Loader2 className="size-4 animate-spin" />
        Creating image…
      </span>
    </div>
  );
}

export function ImageMessage({ imageUrl, fallbackUrls = [], prompt, model, width, height }: Props) {
  const [errored, setErrored] = useState(false);
  const [loading, setLoading] = useState(Boolean(imageUrl));
  const [activeImageUrl, setActiveImageUrl] = useState(imageUrl);
  const [fallbackIndex, setFallbackIndex] = useState(0);

  useEffect(() => {
    setActiveImageUrl(imageUrl);
    setFallbackIndex(0);
    setErrored(false);
    setLoading(Boolean(imageUrl));
  }, [imageUrl]);

  // Match the placeholder's aspect ratio to the real image dimensions so the
  // frame doesn't jump (and appear to "crop" the image) once it finishes
  // loading. Falls back to a square while dimensions are unknown.
  const aspectRatio = width && height ? `${width} / ${height}` : "1 / 1";

  if (!activeImageUrl) {
    return <GeneratingFrame className="w-full max-w-lg" style={{ aspectRatio }} />;
  }

  if (errored) {
    return (
      <div
        className="flex max-w-md gap-3 rounded-2xl border border-destructive/30 bg-destructive/5 p-4"
        role="alert"
      >
        <ImageOff className="mt-0.5 size-5 shrink-0 text-destructive" />
        <div className="min-w-0">
          <p className="m-0 text-sm font-semibold text-destructive">Image could not be generated</p>
          <p className="mt-1 mb-0 text-xs leading-relaxed text-muted-foreground">
            The prompt may not have passed the content filter, or the provider is temporarily
            unavailable. Try rephrasing it.
          </p>
          {prompt ? (
            <p className="mt-1.5 mb-0 text-xs text-muted-foreground/80">Prompt: {prompt}</p>
          ) : null}
        </div>
      </div>
    );
  }

  return (
    <figure className="m-0 max-w-full">
      <div
        className="group relative w-full max-w-lg overflow-hidden rounded-2xl border border-border/70 bg-muted/40 shadow-sm"
        style={{ aspectRatio }}
      >
        {loading ? <GeneratingFrame className="absolute inset-0 rounded-2xl border-0" /> : null}
        <img
          src={activeImageUrl}
          alt={prompt ?? (model ? `Generated by ${model}` : "Generated image")}
          // object-contain (never object-cover) so the full generated
          // image is always shown — nothing gets cropped at the edges.
          className={cn(
            "block size-full object-contain transition-opacity duration-300",
            loading ? "opacity-0" : "opacity-100",
          )}
          onLoad={() => setLoading(false)}
          onError={() => {
            const nextUrl = fallbackUrls[fallbackIndex];
            if (nextUrl) {
              console.warn("[image] selected Pollinations image failed; trying fallback", {
                fallbackIndex: fallbackIndex + 1,
              });
              setFallbackIndex((index) => index + 1);
              setActiveImageUrl(nextUrl);
              setLoading(true);
              return;
            }
            setLoading(false);
            setErrored(true);
          }}
          loading="lazy"
        />
        {!loading ? (
          <Tooltip>
            <TooltipTrigger
              render={
                <Button
                  render={<a href={activeImageUrl} download target="_blank" rel="noreferrer" />}
                  variant="secondary"
                  size="icon-sm"
                  className="absolute top-2.5 right-2.5 bg-background/70 opacity-0 backdrop-blur transition-opacity group-hover:opacity-100 focus-visible:opacity-100"
                  aria-label="Download image"
                />
              }
            >
              <Download />
            </TooltipTrigger>
            <TooltipContent>Download</TooltipContent>
          </Tooltip>
        ) : null}
      </div>

      {prompt && !loading ? (
        <figcaption className="mt-2 flex max-w-lg items-start justify-between gap-3 text-xs leading-relaxed text-muted-foreground">
          <span className="min-w-0">{prompt}</span>
          {width && height ? (
            <Badge variant="outline" className="shrink-0 tabular-nums">
              {width}×{height}
            </Badge>
          ) : null}
        </figcaption>
      ) : null}
    </figure>
  );
}
