import { useEffect, useState } from "react";
import type { ModelId } from "../types";

type Props = {
  imageUrl: string;
  fallbackUrls?: string[];
  prompt?: string;
  model?: ModelId;
  width?: number;
  height?: number;
};

export function ImageMessage({ imageUrl, fallbackUrls = [], prompt, model, width, height }: Props) {
  const [errored, setErrored] = useState(false);
  const [loading, setLoading] = useState(Boolean(imageUrl));
  const [activeImageUrl, setActiveImageUrl] = useState(imageUrl);
  const [fallbackIndex, setFallbackIndex] = useState(0);

  useEffect(() => {
    setActiveImageUrl(imageUrl);
    setFallbackIndex(0);
    setErrored(false);
    setLoading(Boolean(imageUrl));
  }, [imageUrl]);

  // Match the placeholder's aspect ratio to the real image dimensions so the
  // frame doesn't jump (and appear to "crop" the image) once it finishes
  // loading. Falls back to a square while dimensions are unknown.
  const aspectRatio = width && height ? `${width} / ${height}` : "1 / 1";

  if (!activeImageUrl) {
    return (
      <div
        className="image-generation-frame relative flex w-full max-w-180 items-start rounded-xl px-6 py-5 text-[#dbe9ff] max-[640px]:max-w-full"
        style={{ aspectRatio }}
        role="status"
        aria-live="polite"
      >
        <span className="relative z-10 whitespace-nowrap text-lg font-semibold tracking-tight">Creating image</span>
      </div>
    );
  }

  return (
    <div className="max-w-full">
      {errored ? (
        <div className="flex items-start gap-2 rounded-lg border border-red-400/40 bg-red-950/20 p-3" role="alert">
          <span>🖼️</span>
          <div>
            <p className="m-0 font-semibold text-[#ffb4b0]">Image could not be generated.</p>
            <p className="m-0 mt-1 text-sm text-[#91a7c3]">
              This can happen when the request doesn't pass our content safety filter, or the image provider is temporarily unavailable. Try rephrasing the prompt.
            </p>
            {prompt ? <p className="m-0 mt-1 text-sm text-[#91a7c3]">Prompt: {prompt}</p> : null}
          </div>
        </div>
      ) : (
        <>
          <div
            className="group relative w-full max-w-180 overflow-hidden rounded-xl border border-[#294c7d] bg-[#132238] max-[640px]:max-w-full"
            style={{ aspectRatio }}
          >
            {loading ? (
              <div className="image-generation-frame absolute inset-0 flex items-start px-6 py-5 text-[#dbe9ff]" role="status" aria-live="polite">
                <span className="relative z-10 whitespace-nowrap text-lg font-semibold tracking-tight">Creating image</span>
              </div>
            ) : null}
            <img
              src={activeImageUrl}
              alt={prompt ?? model ? `Generated by ${model ?? "model"}` : "Generated image"}
              // object-contain (never object-cover) so the full generated
              // image is always shown — nothing gets cropped at the edges.
              className={`block h-full w-full object-contain transition-opacity duration-300 ${loading ? "opacity-0" : "opacity-100"}`}
              onLoad={() => setLoading(false)}
              onError={() => {
                const nextUrl = fallbackUrls[fallbackIndex];
                if (nextUrl) {
                  console.warn("[image] selected Pollinations image failed; trying fallback", {
                    fallbackIndex: fallbackIndex + 1,
                  });
                  setFallbackIndex((index) => index + 1);
                  setActiveImageUrl(nextUrl);
                  setLoading(true);
                  return;
                }
                setLoading(false);
                setErrored(true);
              }}
              loading="lazy"
            />
            {!loading ? (
              <a
                href={activeImageUrl}
                download
                target="_blank"
                rel="noreferrer"
                className="absolute right-2 top-2 flex h-8 w-8 items-center justify-center rounded-lg bg-black/55 text-[#dbe9ff] opacity-0 backdrop-blur transition-opacity duration-200 hover:bg-black/75 group-hover:opacity-100 focus-visible:opacity-100"
                title="Download image"
                aria-label="Download image"
              >
                ⬇
              </a>
            ) : null}
          </div>
          {prompt && !loading ? (
            <p className="m-0 mt-2 flex items-start justify-between gap-2 text-sm text-[#91a7c3]">
              <span>
                <strong>Prompt:</strong> {prompt}
              </span>
              {width && height ? (
                <span className="shrink-0 whitespace-nowrap rounded-full border border-[#294c7d] px-2 py-0.5 text-xs text-[#7db4ff]">
                  {width}×{height}
                </span>
              ) : null}
            </p>
          ) : null}
        </>
      )}
    </div>
  );
}
