import { useState } from "react";
import type { ModelId } from "../types";

type Props = {
  imageUrl: string;
  prompt?: string;
  model?: ModelId;
};

export function ImageMessage({ imageUrl, prompt, model }: Props) {
  const [errored, setErrored] = useState(false);

  if (!imageUrl) return null;

  return (
    <div className="max-w-full">
      {errored ? (
        <div className="rounded-lg border border-red-400/40 bg-red-950/20 p-3" role="alert">
          <span>🖼️</span>
          <p>Image could not be loaded.</p>
          {prompt ? <p className="m-0 text-sm text-[#91a7c3]">Prompt: {prompt}</p> : null}
        </div>
      ) : (
        <>
          <img
            src={imageUrl}
            alt={prompt ?? model ? `Generated by ${model ?? "model"}` : "Generated image"}
            className="block max-h-90 max-w-full rounded-lg border border-[#294c7d] object-contain"
            onError={() => setErrored(true)}
            loading="lazy"
          />
          {prompt ? (
            <p className="m-0 mt-2 text-sm text-[#91a7c3]">
              <strong>Prompt:</strong> {prompt}
            </p>
          ) : null}
        </>
      )}
    </div>
  );
}
